version: "3.7"

services:
  db:
    image: postgres:9.6
    hostname: postgresql
    container_name: space-xplorer-db
    environment:
      POSTGRES_PASSWORD: space-xplorer
      POSTGRES_USER: space-xplorer
      POSTGRES_DB: space-xplorer
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data

  cache:
    image: redis
    hostname: redis
    container_name: space-xplorer-cache
    ports:
      - 6379:6379
    volumes:
      - cache:/data

  migrations:
    image: wyvarn/space-xplorer-migrations:latest
    container_name: space-xplorer-migrations
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://space-xplorer:space-xplorer@localhost:5432/space-xplorer?schema=public

  api:
    image: wyvarn/space-xplorer-api:latest
    hostname: spacexplorer-api
    container_name: space-xplorer-api
    ports:
      - 4000:4000
    depends_on:
      - migrations
      - db
      - cache
    environment:
      CACHE_HOST: localhost
      CACHE_PORT: 6379
      CACHE_USER: user
      CACHE_PASSWORD: password
      CACHE_URI: redis://localhost:6379
      DATABASE_URL: postgresql://space-xplorer:space-xplorer@localhost:5432/space-xplorer?schema=public

volumes:
  db:
  cache:
