# Reference:https://github.com/marketplace/actions/build-and-push-docker-images
name: Space Xplorer Client Docker Image Build

on:
  push:
    branches: [ main, beta, develop ]

jobs:
  push_to_registry:
    name: Push Docker image Github Registry
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: wyvarn/space-xplorer-client/space-xplorer-client
          dockerfile: "Dockerfile"
          tag_with_ref: true